{
 "title": "Reverse Proxy Visualization",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Up time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{job=\"reverse-proxy\"}"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{uri=\"/**\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "targets": [
    { "expr": "system_cpu_usage*100" }
   ]
  },
  {
   "title": "Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{uri!~\"/actuator/.*\"}*1000",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\",job=\"reverse-proxy\"}",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}