#Reference for this file is a Project that I have participated: 
#https://bitbucket.org/obviobrasil/raichu-devops-gcp/src/develop/grafana/values-staging.yaml
#
#Reference for dashboards:
#https://g00glen00b.be/monitoring-spring-prometheus-grafana/
serviceAccount:
  create: true
  name:

replicas: 1

image:
  repository: grafana/grafana
  tag: 6.0.1
  pullPolicy: IfNotPresent

securityContext:
  runAsUser: 472
  fsGroup: 472

service:
  type: ClusterIP
  port: 80
  annotations: {}
  labels: {}

#Admin Credentials
adminUser: admin
adminPassword: admin

# Use an existing secret for the admin user.
admin:
  existingSecret: ""
  userKey: admin-user
  passwordKey: admin-password

datasources:
 datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://marcelo-adobe-prometheus-server.marcelo-test.svc.cluster.local:80
        access: proxy
        isDefault: true
      
## ref: http://docs.grafana.org/administration/provisioning/#dashboards
# dashboardProviders:
#  dashboardproviders.yaml:
#    apiVersion: 1
#    providers:
#    - name: 'default'
#      orgId: 1
#      folder: ''
#      type: file
#      disableDeletion: false
#      editable: true
#      options:
#        path: /var/lib/grafana/dashboards/default

# dashboards: 
 # default:
   # marcelo-reverse-proxy-dashboard:
      # json: grafana-dashboard.json


## Grafana's primary configuration
## ref: http://docs.grafana.org/installation/configuration/
grafana.ini:
  paths:
    data: /var/lib/grafana/data
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  analytics:
    check_for_updates: true
  log:
    mode: console
  grafana_net:
    url: https://grafana.net


## Sidecars that collect the configmaps with specified label and stores the included files them into the respective folders
## Requires at least Grafana 5 to work and can't be used together with parameters dashboardProviders, datasources and dashboards
sidecar:
  image: kiwigrid/k8s-sidecar:0.0.11
  imagePullPolicy: IfNotPresent
  resources:
  dashboards:
    enabled: true
    label: grafana_dashboard
    folder: /tmp/dashboards
    searchNamespace: null
  datasources:
    enabled: true
    label: grafana_datasource
    searchNamespace: null