marceloAdobeTest:
  appName: marcelo-adobe-test
  namespace: marcelo-test
  image:
    repository: marcelovcpereira/adobe-test:1.0.4
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "1500m"
      memory: "4096Mi"
    requests:
      cpu: "1500m"
      memory: "4096Mi"

#########################
# Environment Variables #
#########################
  configMap:
    REVERSE_PROXY_ENVIRONMENT: dev

#######################
# PROXY CONFIGURATION #
#######################
  proxy:
    listen:
      #do not bind to 127.0.0.1 or containar won't be accessible from outside
      address: 0.0.0.0
      port: 9999
    services:
      - name: my-service-a
        domain: a.my-services.com
        strategy: random
        hosts:
          - address: "marcelo-adobe-service-a.marcelo-test.svc.cluster.local"
            port: 9000
      - name: b-service
        domain: b.my-services.com
        strategy: round_robin
        hosts:
          - address: "marcelo-adobe-service-b.marcelo-test.svc.cluster.local"
            port: 8000
          - address: "marcelo-adobe-service-b2.marcelo-test.svc.cluster.local"
            port: 8001
          - address: "marcelo-adobe-service-b3.marcelo-test.svc.cluster.local"
            port: 8002
    exposedManagementEndpoints: health,info,metrics,prometheus
    monitoring:
      prometheus:
        port: 9090
      grafana:
        port: 9898