marceloAdobeTest:
  appName: marcelo-adobe-test
  image:
    repository: marcelovcpereira/adobe-test:1.0.2
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "1500m"
      memory: "4096Mi"
    requests:
      cpu: "1500m"
      memory: "4096Mi"

#########################
# Environment Variables #
#########################
  configMap:
    REVERSE_PROXY_ENVIRONMENT: dev

#######################
# PROXY CONFIGURATION #
#######################
  proxy:
    listen:
      address: "127.0.0.1"
      port: 8888
    services:
      - name: my-service-a
        domain: a.my-services.com
        strategy: random
        hosts:
          - address: "marcelo-adobe-service-a.marcelo-test.svc.cluster.local"
            port: 9000
      # - name: b-service
      #   domain: b.my-services.com
      #   strategy: round_robin
      #   hosts:
      #     - address: "10.0.0.0"
      #       port: 8002
      #     - address: "10.0.0.0"
      #       port: 8003
    exposedManagementEndpoints: health,info,metrics,prometheus
    monitoring:
      prometheus:
        port: 9999
      grafana:
        port: 9898