marceloAdobeTest:
  appName: marcelo-adobe-reverse-proxy
  namespace: marcelo-test
  image:
    repository: marcelovcpereira/adobe-test:1.0.9
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "1500m"
      memory: "4096Mi"
    requests:
      cpu: "1500m"
      memory: "4096Mi"

###############################################
# Environment Variables for the Reverse Proxy #
###############################################
  configMap:
    REVERSE_PROXY_ENVIRONMENT: dev
    REDIS_HOST: "marcelo-adobe-redis.marcelo-test.svc.cluster.local"
    REDIS_PORT: 6379

#######################
# PROXY CONFIGURATION #
#######################
  proxy:
    listen:
      #do not bind to 127.0.0.1 or containar won't be accessible from outside
      address: 0.0.0.0
      port: 9999
    services:
      - name: my-service-a
        domain: a.my-services.com
        strategy: random
        hosts:
          - address: "marcelo-adobe-service-a0.marcelo-test.svc.cluster.local"
            port: 9000
          - address: "marcelo-adobe-service-a1.marcelo-test.svc.cluster.local"
            port: 9000
      - name: b-service
        domain: b.my-services.com
        strategy: round_robin
        hosts:
          - address: "marcelo-adobe-service-b0.marcelo-test.svc.cluster.local"
            port: 8000
          - address: "marcelo-adobe-service-b1.marcelo-test.svc.cluster.local"
            port: 8000
          - address: "marcelo-adobe-service-b2.marcelo-test.svc.cluster.local"
            port: 8000
    exposedManagementEndpoints: health,info,metrics,prometheus
############################
# MONITORING CONFIGURATION #
############################
    monitoring:
      port: 9898
      name: marcelo-adobe-grafana
      prometheusPort: 80
      service:
        type: ClusterIP
      adminUser: admin
      adminPassword: admin
      image:
        repository: grafana/grafana
        tag: 6.0.1
        pullPolicy: IfNotPresent
      rbac:
        create: true
        namespaced: false
        pspEnabled: true
        pspUseAppArmor: true
      serviceAccount:
        create: true
        name: default
      ldap:
          existingSecret: ""
          config: ""
      securityContext:
        runAsUser: 472
        fsGroup: 472
      admin:
        existingSecret: ""
        userKey: admin-user
        passwordKey: admin-password
      grafana.ini:
        paths:
          data: /var/lib/grafana/data
          logs: /var/log/grafana
          plugins: /var/lib/grafana/plugins
          provisioning: /etc/grafana/provisioning
        analytics:
          check_for_updates: true
        log:
          mode: console
        grafana_net:
          url: https://grafana.net
      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
            - name: Prometheus
              type: prometheus
              url: http://prometheus-service.marcelo-test.svc.cluster.local:80
              access: proxy
              isDefault: true
      sidecar:
        image: kiwigrid/k8s-sidecar:0.0.11
        imagePullPolicy: IfNotPresent
        resources:
        dashboards:
          enabled: true
          label: grafana_dashboard
          folder: /tmp/dashboards
          searchNamespace: null
        datasources:
          enabled: true
          label: grafana_datasource
          searchNamespace: null
################################
## Mock Services Configuration #
#################################
  serviceA:
    enabled: true
    replicas: 2
    name: marcelo-adobe-service-a
    image:
      repository: marcelovcpereira/adobe-test:servicea
      pullPolicy: IfNotPresent
    configMap:
      SERVICE_A_PORT: 9000
  serviceB:
    enabled: true
    replicas: 3
    name: marcelo-adobe-service-b
    image:
      repository: marcelovcpereira/adobe-test:serviceb
      pullPolicy: IfNotPresent
    configMap:
      SERVICE_B_PORT: 8000
#######################
# CACHE CONFIGURATION #
#######################
  redis:
    name: marcelo-adobe-redis
    port: 6379