{{- if .Values.marceloAdobeTest.proxy.monitoring.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.marceloAdobeTest.proxy.monitoring.name }}
  labels:
    app: {{ .Values.marceloAdobeTest.proxy.monitoring.name }}
type: Opaque
data:
  admin-user: {{ .Values.marceloAdobeTest.proxy.monitoring.adminUser | b64enc | quote }}
  {{- if .Values.marceloAdobeTest.proxy.monitoring.adminPassword }}
  admin-password: {{ .Values.marceloAdobeTest.proxy.monitoring.adminPassword | b64enc | quote }}
  {{- else }}
  admin-password: {{ randAlphaNum 40 | b64enc | quote }}
  {{- end }}
{{- end }}