{{- if .Values.marceloAdobeTest.proxy.monitoring.enabled }}
{{- if and .Values.marceloAdobeTest.proxy.monitoring.rbac.create (not .Values.marceloAdobeTest.proxy.monitoring.rbac.namespaced) }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.marceloAdobeTest.proxy.monitoring.name }}-clusterrolebinding
  labels:
    app: {{ .Values.marceloAdobeTest.proxy.monitoring.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.marceloAdobeTest.proxy.monitoring.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.marceloAdobeTest.proxy.monitoring.name }}-clusterrole
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}