{{- if .Values.marceloAdobeTest.proxy.monitoring.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.marceloAdobeTest.proxy.monitoring.name }}
  labels:
    app: {{ .Values.marceloAdobeTest.proxy.monitoring.name }}
spec:
{{- if (or (eq .Values.marceloAdobeTest.proxy.monitoring.service.type "ClusterIP") (empty .Values.marceloAdobeTest.proxy.monitoring.service.type)) }}
  type: ClusterIP
  {{- if .Values.marceloAdobeTest.proxy.monitoring.service.clusterIP }}
  clusterIP: {{ .Values.marceloAdobeTest.proxy.monitoring.service.clusterIP }}
  {{end}}
{{- else if eq .Values.marceloAdobeTest.proxy.monitoring.service.type "LoadBalancer" }}
  type: {{ .Values.marceloAdobeTest.proxy.monitoring.service.type }}
  {{- if .Values.marceloAdobeTest.proxy.monitoring.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.marceloAdobeTest.proxy.monitoring.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.marceloAdobeTest.proxy.monitoring.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.marceloAdobeTest.proxy.monitoring.service.loadBalancerSourceRanges | indent 4 }}
  {{- end -}}
{{- else }}
  type: {{ .Values.marceloAdobeTest.proxy.monitoring.service.type }}
{{- end }}
{{- if .Values.marceloAdobeTest.proxy.monitoring.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.marceloAdobeTest.proxy.monitoring.service.externalIPs | indent 4 }}
{{- end }}
  ports:
    - name: service
      port: {{ .Values.marceloAdobeTest.proxy.monitoring.port }}
      protocol: TCP
      targetPort: 3000
{{ if (and (eq .Values.marceloAdobeTest.proxy.monitoring.service.type "NodePort") (not (empty .Values.marceloAdobeTest.proxy.monitoring.service.nodePort))) }}
      nodePort: {{.Values.service.nodePort}}
{{ end }}
  selector:
    app: {{ .Values.marceloAdobeTest.proxy.monitoring.name }}
{{- end }}