#Reference: https://linuxacademy.com/blog/kubernetes/running-prometheus-on-kubernetes/
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config-map
  labels:
    name: prometheus-config-map
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    scrape_configs:
      - job_name: 'reverse-proxy'
        metrics_path: /actuator/prometheus
        scrape_interval: 10s
        static_configs:
          - targets: ['{{.Values.marceloAdobeTest.appName}}.{{.Values.marceloAdobeTest.namespace}}.svc.cluster.local:{{.Values.marceloAdobeTest.proxy.listen.port}}']
