#Reference: https://linuxacademy.com/blog/kubernetes/running-prometheus-on-kubernetes/
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config-map
  labels:
    name: prometheus-config-map
  namespace: monitoring
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    scrape_configs:
      - job_name: 'reverse-proxy'
        metrics_path: /prometheus
        scrape_interval: 10s
        static_configs:
          - targets: ['marcelo-adobe-test.svc.private:9090']
