{{- if .Values.marceloAdobeTest.proxy.monitoring.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: marcelo-adobe-prometheus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.2.1
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
          ports:
            - containerPort: {{ .Values.marceloAdobeTest.proxy.monitoring.prometheusPort }}
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-config-map
{{- end }}