apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.marceloAdobeTest.appName }}
spec:
  ports:
    - port: {{ .Values.marceloAdobeTest.service.port }}
  selector:
    app: {{ .Values.marceloAdobeTest.appName }}
  clusterIP: None